### PR TITLE
Remove strange and broken resources configuration

### LINKED ISSUE #1: Project cannot be built
```
$ mvn clean install
```

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.7:resources (default-resources) on project wscdn-client: Unable to parse configuration of mojo org.apache.maven.plugins:maven-resources-plugin:2.7:resources for parameter resource: Cannot find default setter in class org.apache.maven.plugin.resources.Resource -> [Help 1]

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #1

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/wscdn-client/2)

### CODE REVIEW

**Comment by mstahv** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[pom.xml, line 122 at r1](https://reviewable.io:443/reviews/vaadin/wscdn-client/2#-KS8SALmfBD1mih7giGc:-KS8SALmfBD1mih7giGd:b-qi1s9g) ([raw file](https://github.com/vaadin/wscdn-client/blob/6b908c6e73dc1f084e42583670bbdb9149a9d36a/pom.xml#L122)):_

> ``` XML
>     <build>
> 
>         <resources>
> ```

I have no idea why this is built like this before, nor for which purpose  service.properties is used, but this change breaks its filtering. This should be just like this to keep it working:

```
    <resources>
        <resource>
            <directory>src/main/resources</directory>
            <filtering>true</filtering>
        </resource>
    </resources>
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/wscdn-client/2)_

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[pom.xml, line 122 at r1](https://reviewable.io:443/reviews/vaadin/wscdn-client/2#-KS8SALmfBD1mih7giGc:-KSA-wncuePsHDipY0E-:b-896fix) ([raw file](https://github.com/vaadin/wscdn-client/blob/6b908c6e73dc1f084e42583670bbdb9149a9d36a/pom.xml#L122)):_
<details><summary>

<i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary>



> I have no idea why this is built like this before, nor for which purpose  service.properties is used, but this change breaks its filtering. This should be just like this to keep it working:
> 
> ```
>     <resources>
>         <resource>
>             <directory>src/main/resources</directory>
>             <filtering>true</filtering>
>         </resource>
>     </resources>
> ```
> 
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/wscdn-client/2)_

**Comment by mstahv** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[pom.xml, line 122 at r1](https://reviewable.io:443/reviews/vaadin/wscdn-client/2#-KS8SALmfBD1mih7giGc:-KSA_I0w01ReFCCJTi4X:bpi80yp) ([raw file](https://github.com/vaadin/wscdn-client/blob/6b908c6e73dc1f084e42583670bbdb9149a9d36a/pom.xml#L122)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> Done.
> </details>
> This probably works also, but you could also do the resources config like I suggested. Less weird. Henri (author of that snippet) didn't have a glue why it looks like that.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/wscdn-client/2)_

**Comment by mstahv** [comment]
:lgtm: And you can ignore my comment, I just read the patch from reviewable wrong.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/wscdn-client/2#-:-KSAadFdy6TJ__OzCcIs:b-xw109b)_

**Comment by Artur-** [comment]
Still needs a "review" mark on the file

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/wscdn-client/2#-:-KSD4ByVDNAICtglMH6T:b-yqz2we)_

**Comment by mstahv** [comment]
I already hate this tool.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/wscdn-client/2#-:-KSDWJeeQW4gutXMxX7L:bl8lveu)_

**Comment by mstahv** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/wscdn-client/2)_

**Comment by mstahv** [comment]
I tried everything, now?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/wscdn-client/2#-:-KSDWSh5JXH92fX9j2CM:b-rhqg60)_

**Pull request merged**
